# Generated by Django 3.2.11 on 2022-07-02 11:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=155, null=True)),
                ('short_name', models.CharField(blank=True, max_length=155, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='clan-logo/')),
                ('points', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'clan',
                'verbose_name_plural': 'clans',
                'db_table': 'clan',
                'ordering': ('name',),
            },
        ),
    ]
