# Generated by Django 3.2.11 on 2022-07-02 12:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('clan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClanSquad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=155, null=True)),
                ('member_count', models.IntegerField(blank=True, null=True)),
                ('squad_head_id', models.CharField(blank=True, max_length=155, null=True)),
            ],
            options={
                'verbose_name': 'squad',
                'verbose_name_plural': 'squads',
                'db_table': 'squad',
                'ordering': ('name',),
            },
        ),
        migrations.RenameField(
            model_name='clan',
            old_name='points',
            new_name='clan_point',
        ),
        migrations.AddField(
            model_name='clan',
            name='coins',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='ClanUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=155, null=True)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clan.clan')),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clan.clansquad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
            options={
                'verbose_name': 'clan_user',
                'verbose_name_plural': 'clan_users',
                'db_table': 'clan_user',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='clansquad',
            name='clan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clan.clan'),
        ),
    ]
