# Generated by Django 3.2.11 on 2022-07-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0002_auto_20220702_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='squad_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
