# Generated by Django 3.2.11 on 2022-07-03 06:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('clan', '0003_clan_squad_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClanRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField(blank=True, default='join our clan', max_length=155, null=True)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clan.clan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
            options={
                'verbose_name': 'clan_request',
                'verbose_name_plural': 'clan_request',
                'db_table': 'clan_request',
            },
        ),
    ]
